config/routes.rb
Rails.application.routes.draw do
  resources :pics
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pic.rb
class Pic < ApplicationRecord
    has_many_attached :images


    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: %i[ show edit update destroy ]

  # GET /pics or /pics.json
  def index
    @pics = Pic.order(created_at: :desc)
  end

  # GET /pics/1 or /pics/1.json
  def show
  end

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics or /pics.json
  def create
    @pic = Pic.new(pic_params)

    respond_to do |format|
      if @pic.save
        format.turbo_stream do
          render turbo_stream: [
                             turbo_stream.update('new_pic', 
                                                partial: "pics/form",
                                                locals: { pic: Pic.new }),

                             turbo_stream.append('pics', 
                                                  partial: "pics/pic",
                                                  locals: { pic: @pic })     
                             ]
        end
        format.html { redirect_to pic_url(@pic), notice: "Pic was successfully created." }
        format.json { render :show, status: :created, location: @pic }
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.update('new_pic', 
                                                partial: "pics/form",
                                                locals: { pic: @pic })
        end
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1 or /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to pic_url(@pic), notice: "Pic was successfully updated." }
        format.json { render :show, status: :ok, location: @pic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1 or /pics/1.json
  def destroy
    @pic.destroy

    respond_to do |format|
      format.html { redirect_to pics_url, notice: "Pic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pic_params
      params.require(:pic).permit(:name,images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class= "container mx-auto mt-28 px-5 flex">
    <%= turbo_frame_tag :modal%>
    <%= yield %>
    </main>
  </body>
</html>

app/views/pics/_form.html.erb
<%= form_with(model: pic) do |form| %>
  <% if pic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
        <% pic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class = "my-3"style="margin-left: 200px;">
  <%form.label :images, "Add Images"%>
  <%= form.file_field :images,multiple: true %>
  </div>


  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/pics/_pic.html.erb
<div class= "SingleImage" id="<%= dom_id pic %>">
 <!--
  <p>
    <strong>Name:</strong>
    <%= pic.name %>
  </p>
  -->
  
    
      <p>
      <%if pic.images.attached?%>
        
      <%pic.images.each do |image|%>
      
      
     
      
      <p>
      <%# <%= link_to(image_tag(image), pic) %> %>
      <%= image_tag image,width: "200px" %>
      </p>
      
      <%end%>
      <%end%>

  

</div>
<style>
.SingleImage{
  display:flex;
}
</style>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render "form", pic: @pic %>

<br>

<div>
  <%= link_to "Show this pic", @pic %> |
  <%= link_to "Back to pics", pics_path %>
</div>

app/views/pics/index.html.erb
<p style="color: green"><%= notice %></p>

<div class = "text-center"id= "new_pic">
<h1 >Add Pictures</h1>
<%= render partial: "pics/form",locals: {pic: Pic.new}%>
</div>

<div id="pics">
  <% @pics.each do |pic| %>
    <%= render pic %>
    <p>
      <%# <%= link_to "Show this pic", pic %>
    </p>
  <% end %>
</div>

<%# <%= link_to "New pic", new_pic_path %> 
<style>
#pics{
  display: flex;
  flex-wrap: wrap;
}
</style>

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= render "form", pic: @pic %>

<br>

<div>
  <%= link_to "Back to pics", pics_path %>
</div>

app/views/pics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pic %>

<div>
  <%= link_to "Edit this pic", edit_pic_path(@pic) %> |
  <%= link_to "Back to pics", pics_path %>

  <%= button_to "Destroy this pic", @pic, method: :delete %>
</div>